macOS build action (#334)
* Use Docker Desktop to match local setup

* Add socat

* Remove temporary action trigger

diff --git a/.github/workflows/test-macos.yml b/.github/workflows/test-macos.yml
--- a/.github/workflows/test-macos.yml
+++ b/.github/workflows/test-macos.yml
@@ -10,8 +10,14 @@ jobs:
     name: Build docksal project on macOS
     runs-on: macos-12
     steps:
-      - name: Install docker
-        run: brew install docker docker-machine socat
+      - name: Install Docker Desktop
+        run: |
+          HOMEBREW_NO_AUTO_UPDATE=1 brew install --cask docker
+          brew install socat
+          sudo /Applications/Docker.app/Contents/MacOS/Docker --unattended --install-privileged-components
+          open -a /Applications/Docker.app --args --unattended --accept-license
+          echo "We are waiting for Docker to be up and running. It can take over 2 minutes..."
+          while ! /Applications/Docker.app/Contents/Resources/bin/docker info &>/dev/null; do sleep 1; done
       - name: Run docksal installer
         run: curl -fsSL https://get.docksal.io | bash
       - name: Display docksal system info
