Use Docker Desktop to match local setup

diff --git a/.github/workflows/test-macos.yml b/.github/workflows/test-macos.yml
--- a/.github/workflows/test-macos.yml
+++ b/.github/workflows/test-macos.yml
@@ -2,6 +2,9 @@ name: Test macOS build
 
 on:
   workflow_dispatch: # enable run button on github.com
+  push:
+    branches:
+      - "macos-action"
   schedule:
     - cron: "0 2 7,21 * *" # At 02:00 on day-of-month 7 and 21.
 
@@ -10,8 +13,13 @@ jobs:
     name: Build docksal project on macOS
     runs-on: macos-12
     steps:
-      - name: Install docker
-        run: brew install docker docker-machine socat
+      - name: Install Docker Desktop
+        run: |
+          HOMEBREW_NO_AUTO_UPDATE=1 brew install --cask docker
+          sudo /Applications/Docker.app/Contents/MacOS/Docker --unattended --install-privileged-components
+          open -a /Applications/Docker.app --args --unattended --accept-license
+          echo "We are waiting for Docker to be up and running. It can take over 2 minutes..."
+          while ! /Applications/Docker.app/Contents/Resources/bin/docker info &>/dev/null; do sleep 1; done
       - name: Run docksal installer
         run: curl -fsSL https://get.docksal.io | bash
       - name: Display docksal system info
